version: '3'

services:

  mongodb:
    image: mongo:4.4.10
    container_name: mongodb
    volumes:
      - ./data:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      default:
        ipv4_address: 172.16.0.14
  
  battleship_game:
    image: tybrob/battleship-game:latest
    container_name: battleship_game
    depends_on:
      - mongodb
    networks:
      default:
        ipv4_address: 172.16.0.10

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24