FROM python:3.8.10-alpine

ENV FLASK_APP=battleship_template.py

COPY . /opt/battleship-game

WORKDIR /opt/battleship-game

RUN pip install --upgrade pip

RUN pip install -r /opt/battleship-game/requirements.txt

CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0"]